name: "redpanda-cluster-action"
description: "Setup Redpanda Single or Cluster Mode"
author: "debabrata"
branding:
  icon: fast-forward
  color: red
inputs:
  version:
    description: "Version of Redpanda to use"
    required: false
    default: "latest"
  cluster_mode:
    description: "Whether to run Redpanda in cluster mode"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Start Redpanda
      run: |
        echo "${{ inputs.version }}"
        echo "${{ inputs.cluster_mode }}"
        
        if [ "${{ inputs.cluster_mode }}" = "false" ]; then
          docker compose -f docker-compose-single.yml up -d
        else
          docker compose -f docker-compose-cluster.yml up -d
        fi
      shell: bash
