name: "redpanda-action"
description: "Setup Redpanda"
author: "fernandes"
branding:
  icon: fast-forward
  color: red
inputs:
  version:
    description: "Version of Redpanda to use"
    required: false
    default: "latest"
  cluster-mode:
    description: "Whether to run Redpanda in cluster mode"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
