name: "redpanda"
description: "Setup Redpanda Single or Cluster Mode"
author: "debabrata"
branding:
  icon: fast-forward
  color: red
inputs:
  version:
    description: "Version of Redpanda to use"
    required: false
    default: "latest"
  cluster-mode:
    description: "Whether to run Redpanda in cluster mode"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
